### ISSUE TITLE
Disable keyboard shortcuts in GCODE editor

### ISSUE THREAD

**Issue by sharmstr** [OpenBuilds/OpenBuildsCONTROL#75]
Tried to add a space (using spacebar) in GCODE editor and it started to run the job.  Eeek.

**Comment by openbuilds-engineer** [comment]
Should be sorted in v1.0.166

**Comment by openbuilds-engineer** [comment]
https://github.com/OpenBuilds/OpenBuildsCONTROL/releases/tag/v1.0.166
